insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'BEACON COMMUNITY CENTRE',16);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'BRIMMOND SCHOOL',17);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'DANESTONE CONGREGATIONAL CHURCH',18);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'BALGOWNIE COMMUNITY CENTRE',19);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'KINGSWELLS COMMUNITY CENTRE',20);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'KINGSWELLS COMMUNITY CENTRE',21);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'KINGSWELLS COMMUNITY CENTRE',22);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'KINGSFORD PRIMARY SCHOOL',23);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'SHEDDOCKSLEY COMMUNITY CENTRE',24);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'MUIRFIELD PRIMARY SCHOOL',25);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'SHEDDOCKSLEY BAPTIST CHURCH',26);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'SHEDDOCKSLEY BAPTIST CHURCH',27);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'SHEDDOCKSLEY BAPTIST CHURCH',28);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'SHEDDOCKSLEY BAPTIST CHURCH',29);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'HEATHRYBURN SCHOOL',30);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'L P HENRY E RAE COMMUNITY CENTRE',31);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'MANOR PARK PRIMARY SCHOOL',32);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'NORTHFIELD COMMUNITY CENTRE',33);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'NORTHFIELD COMMUNITY CENTRE',34);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'CUMMINGS PARK COMMUNITY CENTRE',35);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'MASTRICK COMMUNITY CENTRE',36);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'QUARRYHILL PRIMARY SCHOOL',37);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'HILTON COMMUNITY CENTRE',38);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'HILTON COMMUNITY CENTRE',39);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'WOODSIDE COMMUNITY CENTRE',40);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'HIGH CHURCH HILTON',41);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'HIGH CHURCH HILTON',42);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'CAIRNCRY COMMUNITY CENTRE',43);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'CAIRNCRY COMMUNITY CENTRE',44);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'KITTYBREWSTER PRIMARY SCHOOL',45);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'RIVERBANK PRIMARY SCHOOL',46);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'SEATON PRIMARY SCHOOL',47);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'SEATON PRIMARY SCHOOL',48);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'POWIS GATEWAY COMMUNITY CENTRE',49);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'ST MARY''S CHURCH KING STREET',50);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'PITTODRIE STADIUM SIR ALEX FERGUSON LOUNGE',51);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'MIDSTOCKET PARISH CHURCH',52);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'MIDSTOCKET PARISH CHURCH',53);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'ASHGROVE CHILDREN''S CENTRE',54);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'SKENE SQUARE PRIMARY SCHOOL',55);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'CATHERINE STREET COMMUNITY CENTRE',56);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'SUNNYBANK PRIMARY SCHOOL',57);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'CATHERINE STREET COMMUNITY CENTRE',58);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'SEAMOUNT COURT-TENANT''S ROOM',59);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'HANOVER COMMUNITY CENTRE',60);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'HANOVER COMMUNITY CENTRE',61);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'ABERDEEN CITADEL (SALVATION ARMY BUILDING)',62);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'FERNIELEA PRIMARY SCHOOL',63);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'NEW LIFE INTERNATIONAL CHURCH',64);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'ST MARY''S CATHEDRAL HALL',65);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'CATHERINE STREET COMMUNITY CENTRE',66);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'ST PETER''S HERITAGE CENTRE',67);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'PETERCULTER SPORTS CENTRE',68);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'MILLTIMBER COMMUNITY HALL',69);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'ST DEVENICK''S CHURCH HALL',70);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'CULTS KIRK CENTRE',71);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'CULTS KIRK CENTRE',72);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'HAZLEHEAD PRIMARY SCHOOL',73);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'HAZLEHEAD PRIMARY SCHOOL',74);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'ST MARY''S EPISCOPAL CHURCH',75);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'ST MARY''S EPISCOPAL CHURCH',76);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'CRAIGIEBUCKLER CHURCH HALL',77);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'AIRYHALL COMMUNITY CENTRE',78);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'QUEEN''S CROSS PARISH CHURCH',79);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'HOLBURN WEST CHURCH',80);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'HOLBURN WEST CHURCH',81);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'SCHOOL-BRAESIDE PLACE',82);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'MANNOFIELD CHURCH CENTENARY HALL',83);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'MANNOFIELD CHURCH CENTENARY HALL',84);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'RUTHRIESTON OUTDOOR SPORTS CENTRE-PAVILION',85);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'ST FRANCIS CHURCH HALL',86);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'KAIMHILL COMMUNITY CENTRE',87);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'KAIMHILL COMMUNITY CENTRE',88);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'RUTHRIESTON COMMUNITY CENTRE',89);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'FERRYHILL COMMUNITY CENTRE',90);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'FERRYHILL COMMUNITY CENTRE',91);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'FERRYHILL COMMUNITY CENTRE',92);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'SOUTH HOLBURN CHURCH',93);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'FERRYHILL CHURCH HALL',94);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'TORRY YOUTH AND LEISURE CENTRE',95);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'OLD TORRY COMMUNITY CENTRE',96);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'TULLOS SCHOOL',97);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'BALNAGASK COMMUNITY CENTRE',98);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'ABBOTSWELL PRIMARY SCHOOL',99);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'KINCORTH COMMUNITY CENTRE',100);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'ALTENS COMMUNITY CENTRE',101);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'ABBOTSWELL PRIMARY SCHOOL',102);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'KINCORTH COMMUNITY CENTRE',103);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'LOIRSTON ANNEXE',104);
insert into psm.hierarchy_value (organization_id,hierarchy_id,value,parent_id) values (5,14,'LOIRSTON ANNEXE',105);